# Generated by Django 3.0.6 on 2020-05-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('unit_cost', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('times_to_roll', models.IntegerField()),
            ],
        ),
    ]
